### PR TITLE
Fix skin rendering

### LINKED ISSUE #14: semi-transparent 2nd skin layers are opaque
semi-transparent pixels on the hat layer of my skin are rendered opaque. this is not expected behavior and does not match behavior in other mods which fix skins in beta

### PR DESCRIPTION
**Pull request by forkiesassds**
Disabled backface culling during first person hand rendering and fixed semi-translucent outer layers rendering opaque. Fixes #14

### CODE REVIEW

File: src/main/java/pl/js6pak/mojangfix/mixin/client/skin/PlayerEntityRendererMixin.java [hunk 1]
```diff
@@ -40,8 +41,30 @@ public void setThinArms(boolean thinArms) {
...
+            at = @At(value = "INVOKE", target = "Lnet/minecraft/client/render/entity/LivingEntityRenderer;render(Lnet/minecraft/entity/LivingEntity;DDDFF)V"))
+    private void fixOuterLayer$1(CallbackInfo ci) {
+        GL11.glEnable(GL11.GL_BLEND);
+        GL11.glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
+    }
+
+    @Inject(method = "render(Lnet/minecraft/entity/player/PlayerEntity;DDDFF)V", at = @At("RETURN"))
+    private void fixOuterLayer$2(CallbackInfo ci) {
+        GL11.glDisable(GL11.GL_BLEND);
+        GL11.glEnable(GL11.GL_CULL_FACE);
```
Comment (js6pak) [inline src/main/java/pl/js6pak/mojangfix/mixin/client/skin/PlayerEntityRendererMixin.java:68]: We don't disable it, so is this line needed?

**Review by js6pak — CHANGES_REQUESTED** [review]
Thank you!

**Review by js6pak — APPROVED** [review]
